# Generated by Django 4.2.2 on 2023-08-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycrm', '0002_record_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='profile_image',
            new_name='profile_iamge',
        ),
    ]
